---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# SSranef

<!-- badges: start -->
<!-- badges: end -->

The goal of SSranef is to ...

## Installation


And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("josue-rodriguez/SSranef")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(SSranef)
library(rjags)

d <- lme4::sleepstudy
```


```{r}
d$y <- c(scale(d$Reaction))
alpha <- ss_ranef_alpha(y = d$y, unit = d$Subject)
posterior_summary(alpha, ci = 0.90, digits = 2)
ranef_summary(alpha, ci = 0.95, digits = 2)
```

```{r}
beta <- ss_ranef_beta(y = d$y, X = d$Days, unit = d$Subject)
posterior_summary(beta, digits = 2)
ranef_summary(beta, digits = 2)
```

```{r include=FALSE, eval=FALSE}
library(lme4)
summary(lmer(y ~ 1 + (1|Subject), data = d))
```

